TrajectoryPlannerROS:
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_theta: 3.2
  max_vel_x: 1.0   
  min_vel_x: 0.025   
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_rotational_vel: 0.2
  escape_vel: -0.1
  holonomic_robot: false